<a href="https://colab.research.google.com/github/iAmVickster/colab-code/blob/master/percptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PERCEPTRON

###Importing Library

In [24]:
from numpy import array,dot,random
from random import choice

###Activation function

In [25]:
activationfn = lambda x: 0 if x<0 else 1

###Training Dataset


In [26]:
dataset = [
           (array([0,0,1]), 0),
           (array([0,1,1]), 1),
           (array([1,0,1]), 1),
           (array([1,1,1]), 1)
           ]
print(dataset)

[(array([0, 0, 1]), 0), (array([0, 1, 1]), 1), (array([1, 0, 1]), 1), (array([1, 1, 1]), 1)]


###Initializing random numbers for Weights

In [27]:
weights = random.rand(3)
print(weights)

[0.75123192 0.79309871 0.29091613]


###Initializing additional variables

In [28]:
r = 0.2 #learn rate
n = 100 #Iteration count

###Training Model

In [29]:
for i in range(n):
  x, expected = choice(dataset)
  #print(x,expected)
  res = dot(weights, x)
  err = expected-activationfn(res)
  weights += r * err * r

###Evaluating Model

In [30]:
for x, _ in dataset:
  res = dot(x, weights)
  print("Input: {} ResultBAFn: {} ResultAAFn: {}".format(x[:2],round(res, 3),activationfn(res)))


Input: [0 0] ResultBAFn: -0.029 ResultAAFn: 0
Input: [0 1] ResultBAFn: 0.444 ResultAAFn: 1
Input: [1 0] ResultBAFn: 0.402 ResultAAFn: 1
Input: [1 1] ResultBAFn: 0.875 ResultAAFn: 1
